// translate.js - 翻译字典 + TIL 限制判断
// 200+ 医学术语 / 5 大类 / 覆盖 80% 临床试验常用术语

// ============ TIL 限制配置 ============
export const LIMITED_KEYWORDS = [
  'TIL',
  'tumor-infiltrating lymphocyte',
  'tumor infiltrating lymphocytes',
];

export function isLimited(title = '', intervention = '') {
  const text = `${title} ${intervention}`.toLowerCase();
  return LIMITED_KEYWORDS.some(kw => text.includes(kw.toLowerCase()));
}

// ============ 翻译字典(Phase 2:200+ 医学术语) ============
export const TRANSLATION_DICT = {
  // ============ 癌种 70+ ============
  'lung neoplasms': '肺肿瘤',
  'lung cancer': '肺癌',
  'non-small cell lung cancer': '非小细胞肺癌',
  'non-small-cell lung carcinoma': '非小细胞肺癌',
  'small cell lung cancer': '小细胞肺癌',
  'small-cell lung carcinoma': '小细胞肺癌',
  'lung adenocarcinoma': '肺腺癌',
  'lung squamous cell carcinoma': '肺鳞癌',
  'adenocarcinoma of lung': '肺腺癌',
  'squamous cell carcinoma of lung': '肺鳞癌',
  'nsclc': '非小细胞肺癌',
  'sclc': '小细胞肺癌',
  'adenocarcinoma': '腺癌',
  'squamous cell carcinoma': '鳞状细胞癌',
  'large cell carcinoma': '大细胞癌',
  'mesothelioma': '间皮瘤',
  'pleural mesothelioma': '胸膜间皮瘤',
  'breast neoplasms': '乳腺肿瘤',
  'breast cancer': '乳腺癌',
  'triple negative breast cancer': '三阴性乳腺癌',
  'her2 positive breast cancer': 'HER2 阳性乳腺癌',
  'er positive breast cancer': 'ER 阳性乳腺癌',
  'colorectal neoplasms': '结直肠肿瘤',
  'colorectal cancer': '结直肠癌',
  'colon cancer': '结肠癌',
  'rectal cancer': '直肠癌',
  'liver neoplasms': '肝肿瘤',
  'liver cancer': '肝癌',
  'hepatocellular carcinoma': '肝细胞癌',
  'prostate neoplasms': '前列腺肿瘤',
  'prostate cancer': '前列腺癌',
  'gastric neoplasms': '胃肿瘤',
  'gastric cancer': '胃癌',
  'stomach cancer': '胃癌',
  'pancreatic neoplasms': '胰腺肿瘤',
  'pancreatic cancer': '胰腺癌',
  'cervical neoplasms': '宫颈肿瘤',
  'cervical cancer': '宫颈癌',
  'ovarian neoplasms': '卵巢肿瘤',
  'ovarian cancer': '卵巢癌',
  'brain neoplasms': '脑肿瘤',
  'brain cancer': '脑癌',
  'glioma': '神经胶质瘤',
  'glioblastoma': '胶质母细胞瘤',
  'glioblastoma multiforme': '多形性胶质母细胞瘤',
  'meningioma': '脑膜瘤',
  'melanoma': '黑色素瘤',
  'cutaneous melanoma': '皮肤黑色素瘤',
  'uveal melanoma': '眼葡萄膜黑色素瘤',
  'skin neoplasms': '皮肤肿瘤',
  'skin cancer': '皮肤癌',
  'basal cell carcinoma': '基底细胞癌',
  'squamous cell carcinoma': '鳞状细胞癌',
  'leukemia': '白血病',
  'acute myeloid leukemia': '急性髓系白血病',
  'acute lymphoblastic leukemia': '急性淋巴细胞白血病',
  'chronic myeloid leukemia': '慢性髓系白血病',
  'chronic lymphocytic leukemia': '慢性淋巴细胞白血病',
  'lymphoma': '淋巴瘤',
  'non-hodgkin lymphoma': '非霍奇金淋巴瘤',
  'hodgkin lymphoma': '霍奇金淋巴瘤',
  'follicular lymphoma': '滤泡性淋巴瘤',
  'diffuse large b-cell lymphoma': '弥漫大 B 细胞淋巴瘤',
  'mantle cell lymphoma': '套细胞淋巴瘤',
  'multiple myeloma': '多发性骨髓瘤',
  'myelodysplastic syndromes': '骨髓增生异常综合征',
  'myeloproliferative neoplasms': '骨髓增殖性肿瘤',
  'renal cell carcinoma': '肾细胞癌',
  'kidney neoplasms': '肾肿瘤',
  'kidney cancer': '肾癌',
  'bladder cancer': '膀胱癌',
  'urothelial carcinoma': '尿路上皮癌',
  'thyroid neoplasms': '甲状腺肿瘤',
  'thyroid cancer': '甲状腺癌',
  'papillary thyroid carcinoma': '甲状腺乳头状癌',
  'endometrial neoplasms': '子宫内膜肿瘤',
  'endometrial cancer': '子宫内膜癌',
  'esophageal neoplasms': '食管肿瘤',
  'esophageal cancer': '食管癌',
  'head and neck neoplasms': '头颈肿瘤',
  'head and neck cancer': '头颈癌',
  'oral cancer': '口腔癌',
  'laryngeal cancer': '喉癌',
  'renal pelvis carcinoma': '肾盂癌',
  'urachal cancer': '脐尿管癌',
  'anal cancer': '肛门癌',
  'bile duct cancer': '胆管癌',
  'cholangiocarcinoma': '胆管癌',
  'gallbladder cancer': '胆囊癌',
  'small intestine cancer': '小肠癌',
  'neuroendocrine tumors': '神经内分泌肿瘤',
  'carcinoid tumors': '类癌肿瘤',
  'gastrointestinal stromal tumors': '胃肠道间质瘤',
  'gist': '胃肠道间质瘤',
  'sarcoma': '肉瘤',
  'soft tissue sarcoma': '软组织肉瘤',
  'osteosarcoma': '骨肉瘤',
  'ewing sarcoma': '尤文氏肉瘤',
  'mesothelioma': '间皮瘤',
  'thymoma': '胸腺瘤',
  'testicular cancer': '睾丸癌',

  // ============ 药物 / 治疗药物 80+ ============
  'pembrolizumab': '帕博利珠单抗(可瑞达,Keytruda)',
  'nivolumab': '纳武利尤单抗(欧狄沃,Opdivo)',
  'atezolizumab': '阿替利珠单抗(Tecentriq)',
  'durvalumab': '度伐利尤单抗(Imfinzi)',
  'avelumab': '阿维鲁单抗(Bavencio)',
  'ipilimumab': '伊匹木单抗(Yervoy)',
  'cemiplimab': '西米普利单抗(Libtayo)',
  'dostarlimab': '多塔利单抗(Jemperli)',
  'trastuzumab': '曲妥珠单抗(赫赛汀,Herceptin)',
  'pertuzumab': '帕妥珠单抗(帕捷特,Perjeta)',
  'trastuzumab deruxtecan': '曲妥珠单抗-德鲁替康(Enhertu,T-DXd)',
  'trastuzumab emtansine': '曲妥珠单抗-美坦新(T-DM1,Kadcyla)',
  'ado-trastuzumab emtansine': '曲妥珠单抗-美坦新(T-DM1,Kadcyla)',
  'lapatinib': '拉帕替尼(Tykerb)',
  'neratinib': '来那替尼(Nerlynx)',
  'tucatinib': '图卡替尼(Tukysa)',
  'bevacizumab': '贝伐珠单抗(安维汀,Avastin)',
  'ramucirumab': '雷莫芦单抗(Cyramza)',
  'erlotinib': '厄洛替尼(特罗凯,Tarceva)',
  'gefitinib': '吉非替尼(易瑞沙,Iressa)',
  'icotinib': '埃克替尼(凯美纳,Conmana)',
  'osimertinib': '奥希替尼(Tagrisso,AZD9291)',
  'afatinib': '阿法替尼(吉泰瑞,Gilotrif)',
  'dacomitinib': '达可替尼(Visimpro)',
  'amivantamab': 'amivantamab(Rybrevant)',
  'crizotinib': '克唑替尼(赛可瑞,Xalkori)',
  'alectinib': '阿来替尼(安圣莎,Alecensa)',
  'lorlatinib': '劳拉替尼(Lorbrena)',
  'brigatinib': '布格替尼(Alunbrig)',
  'ensartinib': '恩沙替尼(贝美纳)',
  'sotorasib': '索托拉西布(Lumakras,AMG510)',
  'adagrasib': 'adagrasib(Krazati,MRTX849)',
  'olaparib': '奥拉帕利(Lynparza)',
  'rucaparib': '鲁卡帕利(Rubraca)',
  'niraparib': '尼拉帕利(Zejula)',
  'talazoparib': '他拉唑帕利(Talzenna)',
  'veliparib': '维利帕利',
  'vemurafenib': '维莫非尼(Zelboraf)',
  'dabrafenib': '达拉非尼(Tafinlar)',
  'trametinib': '曲美替尼(Mekinist)',
  'cobimetinib': '考比替尼(Cotellic)',
  'binimetinib': '比美替尼(Mektovi)',
  'encorafenib': '恩考非尼(Braftovi)',
  'palbociclib': '帕博西尼(Ibrance)',
  'ribociclib': '瑞博西尼(Kisqali)',
  'abemaciclib': '玻玛西尼(Verzenio)',
  'ibrutinib': '伊布替尼(Imbruvica)',
  'acalabrutinib': '阿卡替尼(Calquence)',
  'zanubrutinib': '泽布替尼(Brukinsa)',
  'lenvatinib': '仑伐替尼(Lenvima)',
  'sorafenib': '索拉非尼(多吉美,Nexavar)',
  'regorafenib': '瑞戈非尼(Stivarga)',
  'sunitinib': '舒尼替尼(索坦,Sutent)',
  'pazopanib': '帕唑帕尼(Votrient)',
  'axitinib': '阿西替尼(Inlyta)',
  'cabozantinib': '卡博替尼(Cabometyx)',
  'vandetanib': '凡德他尼(Caprelsa)',
  'carboplatin': '卡铂(Paraplatin)',
  'cisplatin': '顺铂(Platinol)',
  'oxaliplatin': '奥沙利铂(Eloxatin)',
  'paclitaxel': '紫杉醇(Taxol)',
  'docetaxel': '多西他赛(Taxotere)',
  'nab-paclitaxel': '白蛋白结合型紫杉醇(Abraxane)',
  'gemcitabine': '吉西他滨(Gemzar)',
  'capecitabine': '卡培他滨(Xeloda)',
  '5-fluorouracil': '5-氟尿嘧啶(5-FU)',
  '5-fu': '5-氟尿嘧啶(5-FU)',
  'irinotecan': '伊立替康(Camptosar)',
  'doxorubicin': '多柔比星(阿霉素,Adriamycin)',
  'epirubicin': '表柔比星(Ellence)',
  'liposomal doxorubicin': '脂质体多柔比星(Doxil)',
  'cyclophosphamide': '环磷酰胺(Cytoxan)',
  'temozolomide': '替莫唑胺(Temodar)',
  'vinorelbine': '长春瑞滨(Navelbine)',
  'vinblastine': '长春花碱(Velban)',
  'vincristine': '长春新碱(Oncovin)',
  'etoposide': '依托泊苷(VP-16,Etopophos)',
  'leucovorin': '亚叶酸钙(Leucovorin)',
  'tamoxifen': '他莫昔芬(Nolvadex)',
  'anastrozole': '阿那曲唑(Arimidex)',
  'letrozole': '来曲唑(Femara)',
  'exemestane': '依西美坦(Aromasin)',
  'fulvestrant': '氟维司群(Faslodex)',
  'bicalutamide': '比卡鲁胺(Casodex)',
  'enzalutamide': '恩扎卢胺(Xtandi)',
  'abiraterone': '阿比特龙(Zytiga)',
  'apalutamide': '阿帕鲁胺(Erleada)',
  'darolutamide': '达罗他胺(Nubeqa)',
  'leuprolide': '亮丙瑞林(Lupron)',
  'degarelix': '地加瑞克(Firmagon)',
  'sacituzumab govitecan': 'sacituzumab govitecan(Trodelvy)',
  'enfortumab vedotin': 'enfortumab vedotin(Padcev)',
  'rituximab': '利妥昔单抗(美罗华,Rituxan)',
  'obinutuzumab': '奥妥珠单抗(佳罗华,Gazyva)',
  'aflibercept': '阿柏西普(Eylea,Zaltrap)',
  'tipiracil': 'tipiracil',
  'trifluridine': '曲氟尿苷',
  'tas-102': 'TAS-102(Lonsurf)',
  'selumetinib': '司美替尼(Koselugo)',

  // ============ 治疗方式 25+ ============
  'radiation therapy': '放射治疗',
  'radiotherapy': '放射治疗',
  'chemotherapy': '化疗',
  'immunotherapy': '免疫治疗',
  'targeted therapy': '靶向治疗',
  'hormone therapy': '激素治疗',
  'hormonal therapy': '激素治疗',
  'endocrine therapy': '内分泌治疗',
  'surgery': '手术',
  'surgical resection': '手术切除',
  'stem cell transplant': '干细胞移植',
  'bone marrow transplant': '骨髓移植',
  'car-t therapy': 'CAR-T 治疗',
  'car-t': 'CAR-T 治疗',
  'cart': 'CAR-T 治疗',
  'tisagenlecleucel': 'tisagenlecleucel(Kymriah,CTL019)',
  'axicabtagene ciloleucel': 'axicabtagene ciloleucel(Yescarta)',
  'brexucabtagene autoleucel': 'brexucabtagene autoleucel(Tecartus)',
  'lisocabtagene maraleucel': 'lisocabtagene maraleucel(Breyanzi)',
  'idecabtagene vicleucel': 'idecabtagene vicleucel(Abecma)',
  'maintenance therapy': '维持治疗',
  'consolidation therapy': '巩固治疗',
  'induction therapy': '诱导治疗',
  'neoadjuvant therapy': '新辅助治疗',
  'adjuvant therapy': '辅助治疗',
  'palliative care': '姑息治疗',
  'supportive care': '支持治疗',
  'best supportive care': '最佳支持治疗',
  'placebo': '安慰剂',
  'clinical trial': '临床试验',
  'phase 1': 'I 期',
  'phase 2': 'II 期',
  'phase 3': 'III 期',
  'phase 4': 'IV 期',
  'phase i': 'I 期',
  'phase ii': 'II 期',
  'phase iii': 'III 期',

  // ============ 检查 / 诊断 20+ ============
  'biopsy': '活检',
  'ct scan': 'CT 扫描',
  'mri': '磁共振成像(MRI)',
  'pet scan': 'PET 扫描',
  'pet-ct': 'PET-CT',
  'pet/ct': 'PET-CT',
  'mri scan': '磁共振扫描',
  'x-ray': 'X 光',
  'ultrasound': '超声检查',
  'endoscopy': '内窥镜检查',
  'colonoscopy': '结肠镜检查',
  'gastroscopy': '胃镜检查',
  'mammography': '乳腺 X 光检查',
  'biomarker': '生物标志物',
  'genetic testing': '基因检测',
  'genetic test': '基因检测',
  'liquid biopsy': '液体活检',
  'circulating tumor dna': '循环肿瘤 DNA(ctDNA)',
  'ctdna': '循环肿瘤 DNA',
  'pd-l1': 'PD-L1',
  'pdl1': 'PD-L1',
  'her2': 'HER2',
  'her-2': 'HER2',
  'egfr': 'EGFR',
  'alk': 'ALK',
  'ros1': 'ROS1',
  'kras': 'KRAS',
  'brca': 'BRCA',
  'msi': '微卫星不稳定(MSI)',
  'microsatellite instability': '微卫星不稳定(MSI)',
  'tmb': '肿瘤突变负荷(TMB)',
  'tumor mutational burden': '肿瘤突变负荷(TMB)',

  // ============ 基因突变 10+ ============
  'egfr mutation': 'EGFR 突变',
  'egfr mutated': 'EGFR 突变',
  'egfr-mutated': 'EGFR 突变',
  'egfr positive': 'EGFR 阳性',
  'egfr-positive': 'EGFR 阳性',
  'egfr amplification': 'EGFR 扩增',
  'egfr exon 20': 'EGFR 外显子 20',
  'egfr t790m': 'EGFR T790M 突变',
  'egfr l858r': 'EGFR L858R 突变',
  'alk rearrangement': 'ALK 重排',
  'alk rearranged': 'ALK 重排',
  'alk-rearranged': 'ALK 重排',
  'alk positive': 'ALK 阳性',
  'alk-positive': 'ALK 阳性',
  'alk fusion': 'ALK 融合',
  'ros1 fusion': 'ROS1 融合',
  'ros1 positive': 'ROS1 阳性',
  'ros1 rearrangement': 'ROS1 重排',
  'kras mutation': 'KRAS 突变',
  'kras mutated': 'KRAS 突变',
  'kras g12c': 'KRAS G12C 突变',
  'kras g12d': 'KRAS G12D 突变',
  'kras g12v': 'KRAS G12V 突变',
  'braf mutation': 'BRAF 突变',
  'braf v600e': 'BRAF V600E 突变',
  'braf v600': 'BRAF V600 突变',
  'her2 positive': 'HER2 阳性',
  'her2-negative': 'HER2 阴性',
  'her2 negative': 'HER2 阴性',
  'her2 amplification': 'HER2 扩增',
  'her2 mutant': 'HER2 突变',
  'her2-low': 'HER2 低表达',
  'her2 positive breast cancer': 'HER2 阳性乳腺癌',
  'her2-negative breast cancer': 'HER2 阴性乳腺癌',
  'brca1 mutation': 'BRCA1 突变',
  'brca2 mutation': 'BRCA2 突变',
  'brca mutation': 'BRCA 突变',
  'pik3ca mutation': 'PIK3CA 突变',
  'met amplification': 'MET 扩增',
  'met exon 14': 'MET 外显子 14 跳跃',
  'ret fusion': 'RET 融合',
  'ntrk fusion': 'NTRK 融合',
  'fgfr mutation': 'FGFR 突变',
  'fgfr3 mutation': 'FGFR3 突变',
  'pd-l1 positive': 'PD-L1 阳性',
  'pd-l1 expression': 'PD-L1 表达',
  'pd-l1 high': 'PD-L1 高表达',
  'pd-l1 negative': 'PD-L1 阴性',

  // ============ 分期 / 分级 ============
  'stage iv': 'IV 期',
  'stage iii': 'III 期',
  'stage ii': 'II 期',
  'stage i': 'I 期',
  'metastatic': '转移性',
  'locally advanced': '局部晚期',
  'advanced': '晚期',
  'recurrent': '复发性',
  'refractory': '难治性',
  'unresectable': '不可切除',
  'resectable': '可切除',
  'first-line': '一线',
  'second-line': '二线',
  'first line': '一线',
  'second line': '二线',
  '1l': '一线',
  '2l': '二线',

  // ============ 更多细分癌种 ============
  'renal cell carcinoma': '肾细胞癌',
  'clear cell renal cell carcinoma': '透明细胞肾细胞癌',
  'urothelial carcinoma': '尿路上皮癌',
  'muscle-invasive bladder cancer': '肌层浸润性膀胱癌',
  'non-muscle invasive bladder cancer': '非肌层浸润性膀胱癌',
  'pancreatic ductal adenocarcinoma': '胰腺导管腺癌',
  'pdac': '胰腺导管腺癌',
  'hepatocellular carcinoma': '肝细胞癌',
  'hcc': '肝细胞癌',
  'esophageal squamous cell carcinoma': '食管鳞癌',
  'esophageal adenocarcinoma': '食管腺癌',
  'gastric adenocarcinoma': '胃腺癌',
  'gastroesophageal junction adenocarcinoma': '胃食管交界腺癌',
  'small cell carcinoma': '小细胞癌',
  'merkel cell carcinoma': '梅克尔细胞癌',
  'basal cell carcinoma': '基底细胞癌',
  'cutaneous squamous cell carcinoma': '皮肤鳞状细胞癌',
  'head and neck squamous cell carcinoma': '头颈鳞状细胞癌',
  'hnscc': '头颈鳞状细胞癌',
  'oral squamous cell carcinoma': '口腔鳞状细胞癌',
  'cervical cancer': '宫颈癌',
  'endometrial cancer': '子宫内膜癌',
  'epithelial ovarian cancer': '上皮性卵巢癌',
  'high grade serous ovarian cancer': '高级别浆液性卵巢癌',
  'fallopian tube cancer': '输卵管癌',
  'primary peritoneal cancer': '原发性腹膜癌',
  'thyroid cancer': '甲状腺癌',
  'anaplastic thyroid cancer': '未分化甲状腺癌',
  'medullary thyroid cancer': '甲状腺髓样癌',
  'pheochromocytoma': '嗜铬细胞瘤',
  'paraganglioma': '副神经节瘤',
  'gastrointestinal stromal tumor': '胃肠道间质瘤',
  'gist': '胃肠道间质瘤',
  'neuroendocrine tumor': '神经内分泌肿瘤',
  'net': '神经内分泌肿瘤',
  'well-differentiated neuroendocrine tumor': '高分化神经内分泌肿瘤',
  'poorly differentiated neuroendocrine tumor': '低分化神经内分泌肿瘤',
  'thymic carcinoma': '胸腺癌',
  'kaposi sarcoma': '卡波西肉瘤',
  'mycosis fungoides': '蕈样肉芽肿',
  'sezary syndrome': 'Sézary 综合征',
  'waldenstrom macroglobulinemia': '华氏巨球蛋白血症',
  'acute promyelocytic leukemia': '急性早幼粒细胞白血病',
  'apl': '急性早幼粒细胞白血病',
  't-cell lymphoma': 'T 细胞淋巴瘤',
  'b-cell lymphoma': 'B 细胞淋巴瘤',
  'peripheral t-cell lymphoma': '外周 T 细胞淋巴瘤',
  'ptcl': '外周 T 细胞淋巴瘤',
  'burkitt lymphoma': '伯基特淋巴瘤',
  'marginal zone lymphoma': '边缘区淋巴瘤',
  'waldenstrom': '华氏巨球蛋白血症',
  'chronic lymphocytic leukemia': '慢性淋巴细胞白血病',
  'cll': '慢性淋巴细胞白血病',
  'small lymphocytic lymphoma': '小淋巴细胞淋巴瘤',
  'sll': '小淋巴细胞淋巴瘤',

  // ============ 无连字符/连字符变体 (Phase 3) ============
  'non small cell lung cancer': '非小细胞肺癌',
  'small cell lung cancer': '小细胞肺癌',
  'non small cell lung carcinoma': '非小细胞肺癌',
  'small cell lung carcinoma': '小细胞肺癌',
  'non squamous non small cell lung carcinoma': '非鳞非小细胞肺癌',
  'non-squamous non-small cell lung carcinoma': '非鳞非小细胞肺癌',
  'squamous non-small cell lung carcinoma': '鳞状非小细胞肺癌',
  'squamous non small cell lung carcinoma': '鳞状非小细胞肺癌',
  'limited stage small cell lung cancer': '局限期小细胞肺癌',
  'extensive stage small cell lung cancer': '广泛期小细胞肺癌',
  'limited stage small-cell lung cancer': '局限期小细胞肺癌',
  'extensive-stage small cell lung cancer': '广泛期小细胞肺癌',
  'advanced non-small cell lung cancer': '晚期非小细胞肺癌',
  'advanced non small cell lung cancer': '晚期非小细胞肺癌',
  'recurrent non-small cell lung cancer': '复发性非小细胞肺癌',
  'recurrent non small cell lung cancer': '复发性非小细胞肺癌',
  'metastatic non-small cell lung cancer': '转移性非小细胞肺癌',
  'metastatic non small cell lung cancer': '转移性非小细胞肺癌',
  'metastatic small cell lung cancer': '转移性小细胞肺癌',
  'stage iii non-small cell lung cancer': 'III 期非小细胞肺癌',
  'stage iii non small cell lung cancer': 'III 期非小细胞肺癌',
  'stage iv non-small cell lung cancer': 'IV 期非小细胞肺癌',
  'stage iv non small cell lung cancer': 'IV 期非小细胞肺癌',
  'nsclc stage iii': 'III 期非小细胞肺癌',
  'nsclc stage iv': 'IV 期非小细胞肺癌',
  'nsclc stage ii': 'II 期非小细胞肺癌',
  'nsclc stage i': 'I 期非小细胞肺癌',
  'carcinoma non-small-cell lung': '非小细胞肺癌',
  'carcinoma  non-small-cell lung': '非小细胞肺癌',
  'carcinoma, non-small-cell lung': '非小细胞肺癌',
  'cancer  lung': '肺癌',
  'cancer, lung': '肺癌',
  'cancer metastatic to lung': '肺癌',
  'lung carcinoma': '肺癌',
  'lung tumor': '肺肿瘤',
  'lung tumour': '肺肿瘤',
  'lung neoplasm': '肺肿瘤',
  'cancer, breast': '乳腺癌',
  'breast carcinoma': '乳腺癌',
  'breast tumor': '乳腺肿瘤',
  'breast neoplasm': '乳腺肿瘤',
  'cancer  breast': '乳腺癌',
  'colon carcinoma': '结肠癌',
  'rectal carcinoma': '直肠癌',
  'colon tumor': '结肠肿瘤',
  'cancer, colorectal': '结直肠癌',
  'cancer  colon': '结肠癌',
  'cancer  rectal': '直肠癌',
  'cancer  liver': '肝癌',
  'cancer, liver': '肝癌',
  'cancer  pancreas': '胰腺癌',
  'cancer, pancreas': '胰腺癌',
  'cancer  prostate': '前列腺癌',
  'cancer  ovarian': '卵巢癌',
  'cancer  gastric': '胃癌',
  'cancer  kidney': '肾癌',
  'cancer  bladder': '膀胱癌',
  'cancer  brain': '脑癌',
  'cancer  thyroid': '甲状腺癌',
  'cancer  cervix': '宫颈癌',
  'cancer  endometrial': '子宫内膜癌',
  'cancer  esophageal': '食管癌',
  'cancer  esophageal': '食管癌',
  'cancer  head and neck': '头颈癌',
  'cancer  oral': '口腔癌',
  'cancer  laryngeal': '喉癌',
  'cancer  anal': '肛门癌',
  'cancer  skin': '皮肤癌',
  'cancer  testicular': '睾丸癌',
  'leukemia, myeloid': '髓系白血病',
  'leukemia  myeloid': '髓系白血病',
  'leukemia  lymphocytic': '淋巴细胞白血病',
  'lymphoma, non-hodgkin': '非霍奇金淋巴瘤',
  'lymphoma  non-hodgkin': '非霍奇金淋巴瘤',
  'lymphoma  b-cell': 'B 细胞淋巴瘤',
  'lymphoma  t-cell': 'T 细胞淋巴瘤',
  'carcinoma  hepatocellular': '肝细胞癌',
  'tumor  solid': '实体瘤',
  'tumour  solid': '实体瘤',
  'solid tumor': '实体瘤',
  'solid tumour': '实体瘤',
  'solid tumors': '实体瘤',
  'solid tumours': '实体瘤',
  'advanced cancer': '晚期癌症',
  'metastatic cancer': '转移性癌症',
  'cancer': '癌症',
  'malignant neoplasm': '恶性肿瘤',
  'malignant tumor': '恶性肿瘤',
  'malignant tumour': '恶性肿瘤',
  'benign tumor': '良性肿瘤',
  'benign tumour': '良性肿瘤',
  'tumor': '肿瘤',
  'tumour': '肿瘤',
  'neoplasm': '肿瘤',
  'neoplasms': '肿瘤',
  'cyst': '囊肿',
  'nodule': '结节',
  'pulmonary nodule': '肺结节',
  'solitary pulmonary nodule': '孤立性肺结节',
  'multiple pulmonary nodules': '多发肺结节',
  'lung diseases': '肺疾病',
  'lung disease': '肺疾病',
  'respiratory diseases': '呼吸系统疾病',
  'heart diseases': '心脏病',
  'heart failure': '心力衰竭',
  'atrial fibrillation': '心房颤动',
  'hypertension': '高血压',
  'pulmonary hypertension': '肺动脉高压',
  'diabetes mellitus': '糖尿病',
  'diabetes': '糖尿病',
  'type 2 diabetes': '2 型糖尿病',
  'type 1 diabetes': '1 型糖尿病',
  'asthma': '哮喘',
  'copd': '慢性阻塞性肺病',
  'chronic obstructive pulmonary disease': '慢性阻塞性肺病',
  'sepsis': '败血症',
  'infection': '感染',
  'bacterial infection': '细菌感染',
  'viral infection': '病毒感染',
  'fungal infection': '真菌感染',
  'covid-19': '新冠肺炎',
  'sars-cov-2': '新冠病毒',
  'hiv': '艾滋病病毒',
  'aids': '艾滋病',
  'hepatitis b': '乙型肝炎',
  'hepatitis c': '丙型肝炎',
  'cirrhosis': '肝硬化',
  'fibrosis': '纤维化',
  'pulmonary fibrosis': '肺纤维化',
  'cystic fibrosis': '囊性纤维化',
  'tuberculosis': '结核病',
  'pneumonia': '肺炎',
  'bronchitis': '支气管炎',
  'cardiovascular diseases': '心血管疾病',
  'cardiovascular disease': '心血管疾病',
  'cerebrovascular diseases': '脑血管疾病',
  'stroke': '中风',
  'ischemic stroke': '缺血性中风',
  'myocardial infarction': '心肌梗死',
  'heart attack': '心脏病发作',
  'coronary artery disease': '冠心病',
  'angina': '心绞痛',
  'arrhythmia': '心律失常',
  'sickle cell disease': '镰状细胞病',
  'thalassemia': '地中海贫血',
  'hemophilia': '血友病',
  'anemia': '贫血',
  'iron deficiency anemia': '缺铁性贫血',
  'kidney disease': '肾脏疾病',
  'kidney failure': '肾衰竭',
  'renal failure': '肾衰竭',
  'dialysis': '透析',
  'liver disease': '肝病',
  'liver cirrhosis': '肝硬化',
  'liver metastasis': '肝转移',
  'bone metastasis': '骨转移',
  'brain metastasis': '脑转移',
  'pain': '疼痛',
  'chronic pain': '慢性疼痛',
  'neuropathic pain': '神经性疼痛',
  'migraine': '偏头痛',
  'headache': '头痛',
  'epilepsy': '癫痫',
  'parkinson': '帕金森',
  'parkinson disease': '帕金森病',
  'alzheimer': '阿尔茨海默',
  'alzheimer disease': '阿尔茨海默病',
  'dementia': '痴呆',
  'multiple sclerosis': '多发性硬化',
  'amyotrophic lateral sclerosis': '肌萎缩侧索硬化',
  'sclerosis': '硬化',
  'lupus': '狼疮',
  'rheumatoid arthritis': '类风湿关节炎',
  'osteoarthritis': '骨关节炎',
  'arthritis': '关节炎',
  'psoriasis': '银屑病',
  'eczema': '湿疹',
  'dermatitis': '皮炎',
  'osteoporosis': '骨质疏松',
  'fracture': '骨折',
  'trauma': '创伤',
  'injury': '损伤',
  'obesity': '肥胖',
  'malnutrition': '营养不良',
  'cachexia': '恶病质',
  'pregnancy': '妊娠',
  'infertility': '不孕症',
  'menopause': '更年期',
  'depression': '抑郁症',
  'anxiety': '焦虑症',
  'ptsd': '创伤后应激障碍',
  'autism': '自闭症',
  'adhd': '注意缺陷多动障碍',
  'eating disorders': '进食障碍',
  'anorexia': '厌食症',
  'bulimia': '贪食症',
  'substance abuse': '药物滥用',
  'smoking': '吸烟',
  'alcoholism': '酗酒',
  'vaccination': '疫苗接种',
  'transplantation': '移植',
  'stem cell transplantation': '干细胞移植',
  'organ transplantation': '器官移植',
  'kidney transplantation': '肾移植',
  'liver transplantation': '肝移植',
  'heart transplantation': '心脏移植',
  'lung transplantation': '肺移植',
  'bone marrow transplantation': '骨髓移植',
  'rejection': '排斥反应',
  'graft-versus-host disease': '移植物抗宿主病',
};

// 标准化: 去逗号, 连字符转空格, 多个空格合一
function normalize(text) {
  return text.toLowerCase().trim()
    .replace(/,/g, ' ')
    .replace(/-/g, ' ')
    .replace(/_/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// 尝试多词 substring 匹配
function trySubstringMatch(text) {
  const norm = normalize(text);
  // 把每个 dict key 当正则,看 text 是否包含
  for (const [key, val] of Object.entries(TRANSLATION_DICT)) {
    if (key.length < 5) continue;  // 太短的 key 容易误匹配
    if (norm.includes(key)) return val;
  }
  // 反过来: 看 text 是否是 dict key 的子串
  for (const [key, val] of Object.entries(TRANSLATION_DICT)) {
    if (key.length < 5) continue;
    if (key.includes(norm) && norm.length >= 5) return val;
  }
  return null;
}

export function translate(text, isCondition = false) {
  if (!text) return null;
  const lower = text.toLowerCase().trim();
  if (TRANSLATION_DICT[lower]) {
    return TRANSLATION_DICT[lower];
  }
  // 用标准化后查找 (处理 "non small cell lung cancer" -> "non small cell lung cancer" 不变,但 "carcinoma, non-small-cell lung" 标准化后可能匹配)
  const normalized = normalize(text);
  if (TRANSLATION_DICT[normalized]) {
    return TRANSLATION_DICT[normalized];
  }
  const parts = text.split(/[,;]/).map(p => p.trim()).filter(Boolean);
  if (parts.length > 1) {
    const translated = parts.map(p => {
      const lower = p.toLowerCase();
      if (TRANSLATION_DICT[lower]) return TRANSLATION_DICT[lower];
      const norm = normalize(p);
      if (TRANSLATION_DICT[norm]) return TRANSLATION_DICT[norm];
      // 单个 part 也试 substring
      const sub = trySubstringMatch(p);
      if (sub) return sub;
      return p;
    });
    if (translated.some((t, i) => t !== parts[i])) {
      return translated.join('; ');
    }
  }
  // 最后兜底: substring 匹配
  const sub = trySubstringMatch(text);
  if (sub) return sub;
  return null;
}
